name: 'Pull templates repositories'
description: 'Permit to sync updates from template repositories'
inputs:
  template:  # id of input
    description: 'Template to pull from'
    required: true
  user-email:
    description: 'Git config user email'
    required: true
    default: '90dy+bot@proton.me'
  user-name:
    description: 'Git config user name'
    required: true
    default: 'Just a bot after all'

# outputs:
  # random-number:
    # description: "Random number"
    # value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
    with:
      ref: main

  - name: Include .gitconfig to .git/config
    shell: bash
    run: |
      [ ! -d '.git' ] || git config --local include.path $PWD/.gitconfig

  - name: Set committer infos
    shell: bash
    run: |
      git config --global user.email "${{ inputs.user-email }}"
      git config --global user.name "${{ inputs.user-name }}"

  - name: Pull template
    shell: bash
    run: |
      git fetch template/${{ matrix.template }} || true
      git merge --squash --allow-unrelated-histories template/${{ matrix.template }} -X theirs || true

  # - name: Revert commit update on .github/workflows if WORKFLOW_TOKEN doesn't exists
  #   run: |
  #     [ -z "${{ secrets.WORKFLOW_TOKEN }}" ] \
  #       || git reset -- .github/workflows && git commit --amend --no-edit --no-verify

  - name: Push on repository
    shell: bash
    run: |
      git push -u origin template/${{ matrix.template }}

  - name: Create pull request
    uses: peter-evans/create-pull-request@v5
    with:
      title: Auto upgrade from template
      branch: template/${{ matrix.template }}
