name: Create Tag and release

on:
  push:
    branches:
      - main

jobs:
  automatic-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: phish108/autotag-action@v1.1.64
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
