name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-git-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Include .gitconfig to .git/config
        run: |
          [ ! -d '.git' ] || git config --local include.path $PWD/.gitconfig

      - uses: 90dy/gha-git-sync@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: 90dy/gha-git-sync
          branch: main
          user-email: 90dy+bot@proton.me
          user-name: 90dy

  semantic-release:
    needs: test-git-sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 90dy/gha-semantic-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: main
          plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/git
