name: Test git sync

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-git-sync:
    name: Test git sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Include .gitconfig to .git/config
      run: |
        [ ! -d '.git' ] || git config --local include.path $PWD/.gitconfig

    - uses: 90dy/gha-git-sync@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repository: 90dy/gha-git-sync
        branch: ${{ github.ref_name }}
        user-email: 90dy+bot@proton.me
        user-name: 90dy
